// Launched by run_browser.py against a disposable synthetic library.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
if (!process.env.KARAOKE_TEST_URL) throw Error('Run python player/tests/run_browser.py to create an isolated test library.');
(async()=>{
const browser=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.starts=[];const original=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){window.starts.push(args);return original.apply(this,args);};});
await page.goto(process.env.KARAOKE_TEST_URL);
await page.waitForFunction(()=>window.karaoke?.songs.length>0);
const id=await page.evaluate(()=>karaoke.songs[0].id);
await page.evaluate(id=>karaoke.loadSong(id),id);
await page.waitForFunction(()=>karaoke.player.playing);
await page.evaluate(()=>karaoke.pause());
let state=await page.evaluate(()=>({muted:document.querySelector('video').muted,starts:window.starts,backing:karaoke.player.gains[0].gain.value,position:karaoke.player.position()}));
assert.equal(state.muted,true);assert.deepEqual(state.starts[0],state.starts[1]);assert.equal(state.backing,1);
await page.locator('#vocals').evaluate(n=>{n.value='.65';n.dispatchEvent(new Event('input'));});
await page.evaluate(()=>karaoke.play());
await page.waitForFunction(()=>Math.abs(karaoke.player.gains[1].gain.value-.65)<.005, {}, {timeout:3000});
state=await page.evaluate(()=>({backing:karaoke.player.gains[0].gain.value,vocals:karaoke.player.gains[1].gain.value}));
assert.equal(state.backing,1);assert.ok(Math.abs(state.vocals-.65)<.005, JSON.stringify(state));
await page.evaluate(()=>karaoke.pause());
await page.locator('#seek').evaluate(n=>{n.value='1.5';n.dispatchEvent(new Event('input'));});
assert.equal(await page.evaluate(()=>karaoke.player.position()),1.5);
await page.click('#play');await page.waitForTimeout(100);await page.click('#play');
state=await page.evaluate(()=>window.starts.slice(-2));assert.deepEqual(state[0],state[1]);assert.equal(state[0][1],1.5);
const popupPromise=page.waitForEvent('popup');await page.click('#display');const popup=await popupPromise;await popup.waitForLoadState();
await popup.waitForFunction(()=>document.querySelector('video').getAttribute('src'));
assert.equal(await popup.locator('video').evaluate(n=>n.muted),true);
await page.locator('.edit').first().click();
await page.locator('#edit-form [name=album]').fill('Synthetic album');await page.locator('#edit-form [name=title]').fill('Portable song');await page.locator('#edit-form [name=version]').fill('Live');await page.locator('#edit-form button.primary').click();await page.waitForFunction(()=>karaoke.songs[0].title==='Portable song');
await page.evaluate(id=>karaoke.add(id),id);await page.reload();await page.waitForFunction(()=>window.karaoke?.queue.length===1);
assert.equal(await page.locator('#vocals').inputValue(),'0.65');
await page.click('#play');await page.waitForFunction(()=>karaoke.player.playing);await page.waitForFunction(()=>!karaoke.player.playing&&karaoke.player.position()>3.5,{},{timeout:10000});
await page.click('[data-tab=history]');await page.waitForSelector('.song');
await page.screenshot({path:'/tmp/karaoke-player-test.png',fullPage:true});
assert.deepEqual(errors,[]);await popup.close();await browser.close();console.log('PASS: shared sample schedule, independent vocal gain, pause/seek, audience mute, metadata, local persistence and natural end.');
})().catch(e=>{console.error(e);process.exit(1);});
