// Launched by run-browser.ts against a disposable synthetic library.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
if (!process.env.KARAOKE_TEST_URL) throw Error('Run npm run test:browser to create an isolated test library.');
(async()=>{
const browser=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const expandAlbums=async()=>{for(const toggle of await page.locator('.album-toggle').all())if(await toggle.getAttribute('aria-expanded')==='false')await toggle.click();};
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.starts=[];const original=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){window.starts.push(args);return original.apply(this,args);};});
await page.goto(process.env.KARAOKE_TEST_URL);
await page.waitForFunction(()=>window.karaoke?.songs.length>0);
assert.equal(await page.locator('.song').count(),0);
assert.equal(await page.locator('.album-toggle').count(),1);
await expandAlbums();
const id=await page.evaluate(()=>karaoke.songs[0].id);
await page.evaluate(id=>karaoke.loadSong(id),id);
await page.waitForFunction(()=>karaoke.player.playing);
await page.evaluate(()=>karaoke.pause());
let state=await page.evaluate(()=>({muted:document.querySelector('video').muted,starts:window.starts,backing:karaoke.player.gains[0].gain.value,position:karaoke.player.position()}));
assert.equal(state.muted,true);assert.deepEqual(state.starts[0],state.starts[1]);assert.equal(state.backing,1);
await page.locator('#vocals').evaluate(n=>{n.value='.65';n.dispatchEvent(new Event('input',{bubbles:true}));});
await page.evaluate(()=>karaoke.play());
await page.waitForFunction(()=>Math.abs(karaoke.player.gains[1].gain.value-.65)<.005, {}, {timeout:3000});
state=await page.evaluate(()=>({backing:karaoke.player.gains[0].gain.value,vocals:karaoke.player.gains[1].gain.value}));
assert.equal(state.backing,1);assert.ok(Math.abs(state.vocals-.65)<.005, JSON.stringify(state));
await page.evaluate(()=>karaoke.pause());
await page.locator('#seek').evaluate(n=>{n.value='1.5';n.dispatchEvent(new Event('input',{bubbles:true}));});
assert.equal(await page.evaluate(()=>karaoke.player.position()),1.5);
await page.click('#play');await page.waitForTimeout(100);await page.click('#play');
state=await page.evaluate(()=>window.starts.slice(-2));assert.deepEqual(state[0],state[1]);assert.equal(state[0][1],1.5);
await page.context().addInitScript(()=>{if(location.pathname==='/display') window.requestAnimationFrame=()=>0;});
const popupPromise=page.waitForEvent('popup');await page.click('#display');const popup=await popupPromise;await popup.waitForLoadState();
await popup.waitForFunction(()=>document.querySelector('video').getAttribute('src'));
assert.equal(await popup.locator('video').evaluate(n=>n.muted),true);
await page.evaluate(()=>karaoke.seek(.8));
await popup.waitForFunction(()=>Math.abs(document.querySelector('video').currentTime-.8)<.12);

await page.locator('.edit').first().click();
await page.locator('#edit-form [name=album]').fill('Synthetic album');await page.locator('#edit-form [name=title]').fill('Portable song');await page.locator('#edit-form [name=version]').fill('Live');await page.locator('#edit-form button.primary').click();await page.waitForFunction(()=>karaoke.songs[0].title==='Portable song');
await page.evaluate(id=>karaoke.add(id),id);await page.reload();await page.waitForFunction(()=>window.karaoke?.queue.length===1);
assert.equal(await page.locator('#vocals').inputValue(),'0.65');
await page.click('#play');await page.waitForFunction(()=>karaoke.player.playing);await page.waitForFunction(()=>!karaoke.player.playing&&karaoke.player.position()>3.5,{},{timeout:10000});
await page.click('[data-tab=history]');await page.waitForSelector('.song');
await page.screenshot({path:'/tmp/karaoke-player-test.png',fullPage:true});
// Exercise the React import form, version grouping, queue actions and narrow layout.
await page.click('#import-open');
await page.locator('#import-form [name=files]').setInputFiles(process.env.KARAOKE_TEST_MEDIA_FILE);
await page.locator('#import-form [name=album]').fill('Synthetic album');
await page.locator('#import-form [name=title]').fill('Portable song');
await page.locator('#import-form [name=version]').fill('Album');
await page.click('#import-submit');
await page.waitForFunction(()=>karaoke.songs.length===2);
await page.click('[data-tab=library]');await expandAlbums();
assert.equal(await page.locator('.song').count(),1);
assert.equal(await page.locator('.version').count(),2);
await page.locator('#search').fill('no matching song');
assert.equal(await page.locator('.song').count(),0);
await page.locator('#search').fill('');await expandAlbums();
await page.getByRole('button',{name:'点歌',exact:true}).first().click();
const firstVersion=page.locator('.version').nth(0), secondVersion=page.locator('.version').nth(1);
assert.deepEqual(await firstVersion.locator('.queue-position').allTextContents(),['1']);
assert.equal(await secondVersion.locator('.queue-position').count(),0);
await secondVersion.locator('.queue-request').click();
await firstVersion.locator('.queue-request').hover();
assert.equal(await firstVersion.locator('.queue-request-again').isVisible(),true);
await firstVersion.locator('.queue-request').click();
assert.deepEqual(await firstVersion.locator('.queue-position').allTextContents(),['1','3']);
assert.deepEqual(await secondVersion.locator('.queue-position').allTextContents(),['2']);
await page.locator('#search').hover();
assert.equal(await firstVersion.locator('.queue-request-idle').isVisible(),true);
await page.reload();await page.waitForFunction(()=>karaoke.queue.length===3);await expandAlbums();
assert.deepEqual(await firstVersion.locator('.queue-position').allTextContents(),['1','3']);
await page.click('[data-tab=queue]');
await page.locator('.song').nth(2).getByRole('button',{name:'上移',exact:true}).click();
await page.locator('.song').first().getByRole('button',{name:'移除',exact:true}).click();
await page.click('[data-tab=library]');await expandAlbums();
assert.deepEqual(await firstVersion.locator('.queue-position').allTextContents(),['1']);
assert.deepEqual(await secondVersion.locator('.queue-position').allTextContents(),['2']);
await page.click('[data-tab=queue]');
await page.locator('.song').first().getByRole('button',{name:'移除',exact:true}).click();
await page.click('[data-tab=library]');await expandAlbums();
assert.equal(await firstVersion.locator('.queue-position').count(),0);
assert.equal(await firstVersion.getByRole('button',{name:'点歌',exact:true}).count(),1);
assert.deepEqual(await secondVersion.locator('.queue-position').allTextContents(),['1']);
await page.click('[data-tab=queue]');
assert.equal(await page.locator('.song').count(),1);
await page.getByRole('button',{name:'移除',exact:true}).click();
assert.equal(await page.locator('.song').count(),0);
// File drops must open the import form without navigating the app.
const transfer=await page.evaluateHandle(bytes=>{const dt=new DataTransfer();dt.items.add(new File([new Uint8Array(bytes)],'Dragged.MP4',{type:'video/mp4'}));dt.items.add(new File(['text'],'ignore.txt',{type:'text/plain'}));return dt;},Array.from(require('node:fs').readFileSync(process.env.KARAOKE_TEST_MEDIA_FILE)));
await page.locator('.collection').dispatchEvent('dragenter',{dataTransfer:transfer});
assert.equal(await page.locator('.drop-overlay').count(),1);
await page.locator('.collection').dispatchEvent('drop',{dataTransfer:transfer});
assert.equal(await page.locator('.drop-overlay').count(),0);
assert.equal(await page.locator('#import-dialog').evaluate(n=>n.open),true);
assert.equal(await page.locator('#import-form [name=files]').evaluate(n=>n.files.length),1);
await page.click('#import-submit');
await page.waitForFunction(()=>karaoke.songs.length===3);
assert.ok(await page.evaluate(()=>karaoke.songs.every(s=>/^[a-f0-9]{64}$/.test(s.sha256))));
assert.equal(await page.locator('#database-export').count(),0);
assert.equal(await page.locator('#display svg.lucide').count(),1);
await transfer.dispose();
await page.click('[data-tab=library]');await expandAlbums();
// Reorder distinct songs while keeping the two versions of a song together.
const draggedId=await page.evaluate(()=>karaoke.songs.find(s=>s.original_filename==='Dragged.MP4').id);
await page.evaluate(async id=>{await karaoke.api('/api/songs/'+id,'PATCH',{album:'Synthetic album'});await karaoke.refresh();},draggedId);
await expandAlbums();
const sourceHandle=page.locator(`[data-song-id="${draggedId}"] .song-drag-handle`);
const targetCard=page.locator('.song').first();
await sourceHandle.dragTo(targetCard,{targetPosition:{x:25,y:4}});
await page.waitForFunction(id=>document.querySelector('.song')?.getAttribute('data-song-id')===id,draggedId);
assert.equal(await page.locator('#import-dialog').evaluate(n=>n.open),false);
assert.equal(await page.locator('.song').nth(1).locator('.version').count(),2);
await page.reload();await page.waitForFunction(()=>karaoke.songs.length===3);
assert.equal(await page.locator('.song').count(),0);
await expandAlbums();
assert.equal(await page.locator('.song').first().getAttribute('data-song-id'),draggedId);
await page.locator('.song-drag-handle').first().focus();await page.keyboard.press('ArrowDown');
await page.waitForFunction(id=>document.querySelector('.song')?.getAttribute('data-song-id')!==id,draggedId);
await page.screenshot({path:'/tmp/karaoke-album-sorting.png',fullPage:true});
// Album dragging uses the icon, never expands it or opens file import.
await page.evaluate(async id=>{await karaoke.api('/api/songs/'+id,'PATCH',{album:'Z album'});await karaoke.refresh();},draggedId);
await page.reload();await page.waitForFunction(()=>karaoke.songs.length===3);
const albumNames=()=>page.locator('.library-album').evaluateAll(nodes=>nodes.map(n=>n.dataset.album));
assert.deepEqual(await albumNames(),['Synthetic album','Z album']);
const albumHandle=page.locator('[data-album="Z album"] .album-drag-handle');
await albumHandle.hover();
await page.waitForFunction(()=>getComputedStyle(document.querySelector('[data-album="Z album"] .album-grip-icon')).opacity==='1');
await albumHandle.dragTo(page.locator('.library-album').first(),{targetPosition:{x:100,y:3}});
await page.waitForFunction(()=>document.querySelector('.library-album').dataset.album==='Z album');
assert.equal(await page.locator('[data-album="Z album"] .album-toggle').getAttribute('aria-expanded'),'false');
assert.equal(await page.locator('#import-dialog').evaluate(n=>n.open),false);
await page.reload();await page.waitForFunction(()=>karaoke.songs.length===3);
assert.deepEqual(await albumNames(),['Z album','Synthetic album']);
await page.locator('.album-drag-handle').first().focus();await page.keyboard.press('ArrowDown');
await page.waitForFunction(()=>document.querySelector('.library-album').dataset.album==='Synthetic album');
// Collapsing retains contents while height decreases, then removes hidden controls.
await expandAlbums();await page.waitForTimeout(280);
const heights=await page.locator('.album-toggle').first().evaluate(button=>new Promise(resolve=>{
 const panel=document.getElementById(button.getAttribute('aria-controls'));
 const values=[panel.getBoundingClientRect().height],start=performance.now();button.click();
 function sample(){values.push(panel.getBoundingClientRect().height);if(performance.now()-start<340)requestAnimationFrame(sample);else resolve(values);}requestAnimationFrame(sample);
}));
assert.ok(heights[0]>0);assert.ok(heights.some(h=>h>1&&h<heights[0]-1));assert.ok(heights.at(-1)<1);
assert.equal(await page.locator('.library-album').first().locator('.song').count(),0);
await page.locator('.album-toggle').first().press('Space');
await page.waitForFunction(()=>document.querySelector('.album-toggle').getAttribute('aria-expanded')==='true');
await page.screenshot({path:'/tmp/karaoke-album-drag-animation.png',fullPage:true});
const originalWidth=(await page.locator('.collection').boundingBox()).width;
const separator=page.getByRole('separator',{name:'调整播放区与曲库宽度'});
const handle=await separator.boundingBox();
await page.mouse.move(handle.x+handle.width/2,handle.y+180);await page.mouse.down();
await page.mouse.move(handle.x-150,handle.y+180,{steps:12});await page.mouse.up();
const resizedWidth=(await page.locator('.collection').boundingBox()).width;
assert.ok(resizedWidth>originalWidth+120);
await page.reload();await page.waitForFunction(()=>karaoke.songs.length===3);
assert.ok(Math.abs((await page.locator('.collection').boundingBox()).width-resizedWidth)<2);
await separator.focus();await separator.press('ArrowRight');
assert.ok((await page.locator('.collection').boundingBox()).width<resizedWidth-15);
await page.screenshot({path:'/tmp/karaoke-compact-resizable.png',fullPage:true});
await separator.dblclick();
assert.ok(Math.abs((await page.locator('.collection').boundingBox()).width-originalWidth)<2);
await page.setViewportSize({width:390,height:844});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
assert.equal(await separator.isVisible(),false);
// Album file drops use the first saved song, including collapsed and filtered albums.
await page.setViewportSize({width:1440,height:1050});
await page.evaluate(async()=>{
  const ids=karaoke.songs.map(s=>s.id);
  for (let i=0;i<ids.length;i++) await karaoke.api('/api/songs/'+ids[i],'PATCH',{
    album:i<2?'Drop target':'Other album',title:i===0?'A first':'Z later',artist:i===0?'First artist':'Later artist',version:i===0?'First live':'Later version'
  });
  await karaoke.api('/api/library/order','POST',{album:'Drop target',song_ids:ids.slice(0,2)});
  await karaoke.refresh();
});
const albumFiles=await page.evaluateHandle(bytes=>{
  const dt=new DataTransfer();
  for(const name of ['Album drop one.mp4','Album drop two.mp4'])dt.items.add(new File([new Uint8Array(bytes)],name,{type:'video/mp4'}));
  return dt;
},Array.from(require('node:fs').readFileSync(process.env.KARAOKE_TEST_MEDIA_FILE)));
const albumTarget=page.locator('[data-album="Drop target"]');
const assertAlbumDefaults=async()=>{
  for(const [key,value] of Object.entries({album:'Drop target',artist:'First artist',version:'First live',title:''}))
    assert.equal(await page.locator(`#import-form [name=${key}]`).inputValue(),value);
  assert.equal(await page.locator('#import-form [name=files]').evaluate(n=>n.files.length),2);
};
assert.equal(await albumTarget.locator('.album-toggle').getAttribute('aria-expanded'),'false');
await albumTarget.locator('.album-info strong').dispatchEvent('dragenter',{dataTransfer:albumFiles});
await albumTarget.locator('.album-info strong').dispatchEvent('dragover',{dataTransfer:albumFiles});
assert.equal(await page.locator('.file-drop-target').count(),1);
assert.ok((await page.locator('.drop-overlay').innerText()).includes('Drop target'));
await albumTarget.locator('.album-info strong').dispatchEvent('drop',{dataTransfer:albumFiles});
await assertAlbumDefaults();
assert.equal(await page.locator('.drop-overlay').count(),0);
await page.getByRole('button',{name:'取消',exact:true}).click();
// A regular import must not retain the previous album defaults.
await page.click('#import-open');
for(const key of ['album','artist','version'])assert.equal(await page.locator(`#import-form [name=${key}]`).inputValue(),'');
await page.getByRole('button',{name:'取消',exact:true}).click();
await page.locator('.collection').dispatchEvent('drop',{dataTransfer:albumFiles});
for(const key of ['album','artist','version'])assert.equal(await page.locator(`#import-form [name=${key}]`).inputValue(),'');
await page.getByRole('button',{name:'取消',exact:true}).click();
await page.locator('#search').fill('Z later');
await page.waitForFunction(()=>document.querySelector('[data-album="Drop target"] .song-title')?.textContent==='Z later');
await albumTarget.locator('.song-title').dispatchEvent('drop',{dataTransfer:albumFiles});
await assertAlbumDefaults();
await page.locator('#import-form [name=version]').fill('Edited live');
await page.click('#import-submit');
await page.waitForFunction(()=>karaoke.songs.length===5);
const imported=await page.evaluate(()=>karaoke.songs.filter(s=>s.original_filename?.startsWith('Album drop ')));
assert.equal(imported.length,2);
assert.ok(imported.every(s=>s.album==='Drop target'&&s.artist==='First artist'&&s.version==='Edited live'));
await albumFiles.dispose();
assert.deepEqual(errors,[]);await popup.close();await browser.close();console.log('PASS: playback, metadata, sorting, album drop defaults, filtered/collapsed targets and batch import.');
})().catch(e=>{console.error(e);process.exit(1);});
